# Generated by Django 6.0.6 on 2026-06-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.URLField(),
        ),
    ]
