# Generated by Django 6.0.6 on 2026-06-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='slug',
            field=models.SlugField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
